### ISSUE TITLE
API Authentication Documentation is invalid

### ISSUE THREAD

**Issue by NyCodeGHG** [Traewelling/traewelling#1214]
**Describe the bug**

The docs say that authentication is done via the "Authorization" Header and an api key. The Swagger Playground also does requests with an `Authorization: <apiKey>` header, but that does not work. The correct format would be `Authorization: Bearer <apiKey>`.

**To Reproduce**

1. Go to the [API Playground](https://traewelling.de/api/documentation)
2. Login with your account to create a new token and save the token in the dashboard
3. Try calling the /auth/user endpoint in the playground.
4. The request will be denied with the reason "Unauthenticated"

**Expected behavior**

The documentation should have the correct [openapi definition for a Bearer Token](https://swagger.io/docs/specification/authentication/bearer-authentication/)

**Additional context**

I tried fixing it myself, but i couldn't get the generation of the openapi json file to work.

/cc @DRSchlaubi

**Comment by HerrLevin** [comment]
I tried fixing it but the swagger-generator we're using doesn't seem to support bearerToken correctly. (The official way in their documentation is a notice to prepend "Bearer" in the header. 💀)

I've tried going through this thread (https://github.com/DarkaOnLine/L5-Swagger/issues/57) but decided to scrap it, since we'll be replacing the bearer-auth with oauth. #1216 will include the notice in the "official" way.
