### ISSUE TITLE
Add "Gleitzeit" For check-Ins

### ISSUE THREAD

**Issue by ChillLP** [Traewelling/traewelling#1321]
Sometimes Hafas has Times that Arendt 100% correct and prevent you from checking into a new Connection because the changeover was -2 mins or alike, so a 5 mins "Gleitzeit" (time where checkins can overlap) or alike would be nice

**Comment by MrKrisKrisu** [comment]
We already have an overlapping check and allow up to 10 minutes before and after a check-in. For journeys less then 10 minutes long there is no overlapping check (would be useless because of the tolerance).

If the new check-in overlaps more then 10 minutes you can force the check-in. So I'm not sure if there is some action needed?

https://github.com/Traewelling/traewelling/blob/f3e993ad3e53c8a013097c2750b0882ddbbf20b7/app/Http/Controllers/TransportController.php#L121-L123

**Comment by ChillLP** [comment]
Well, forcing checkin Always loses Points. But ok, my bad.

**Comment by ChristianTacke** [comment]
I would like to ask about "Gleitzeit" relating to checkins and the points: Especially checking into busses that only travel a few stations can be tricky: Let's assume the bus normally starts at 9:00 and ends at 9:05. Now give it 5 minutes delay (that traewelling doesn't know about yet). So if you enter the bus at 9:05 and need a minute to fill the form, you're checking in at 9:06. 1 minute too late to get the full points.
