### ISSUE TITLE
Better Issue handling on Github

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1421]
**Is your feature request related to a problem? Please describe.**
My problem is that most Issues just get unkept.
Like Issue #1349, someone already gave the Solution and the Code to fix the Bug in the Comments but wasn't able to fix it themselves because Träwelling didn't work for them locally. And now the Solution to fix the Bug is stated in the Comments of the Bug but no one contemplate to implement it.
Not even Contributors of the Git-Repo. From the Comments of the Contributors on the same issue it sounded like they are inexperienced in this Issue even if it's a small and easy fix as I see from the other comments.

That happens not only on the stated Issue, it happens in multiple Issues.

**Describe the solution you'd like**
Using the Gits Issues system for Bugs or enhancements is a good Start, but the execution of it is very poor.
It would be better to use the Agile way with Scrum for Issues and using the Assign, Milestone, Labels and Projects system better.
With Scrum, you would be able to plan Sprints and define Story points and assign Issues to Contributors which has the know-how for the issue, instead of letting an issue open for months without someone even looking at it at some point.
If no one has enough Know-How, you could use your Discord Server better asking peoples if they know how to implement it. Like back to the Issue, the Git Contributor that commented on it didn't know how to do it but someone else does and as far as I know they are on the Discord too, so you could ask them on the Discord.

**Describe alternatives you've considered**
Alternatives would be not using the Issues System of GitHub if the issues just get ignored anyway or never get implemented.
One Alternative would be using better Systems like Jira, but those cost money, or just create an own System in Träwelling.

**Comment by MrKrisKrisu** [comment]
Träwelling is an OpenSource project developed and run by various people in their spare time. If no one has time or desire to work on issues then nothing happens. All people who are in the "core team" are fully employed or otherwise fully occupied. Sometimes something happens, sometimes not. If you are not satisfied, you are welcome to create pull requests.

**Comment by Oxbowatos** [comment]
@MrKrisKrisu Are you saying that no one has time to implement one line of code in a CSS file for about three weeks?

Furthermore, you were clearly unaware of how to implement it and that CSS was able to do it.
It seems to me that you are not experienced enough in web development to implement one line of CSS code, or you would already have done it by now

**Comment by jeyemwey** [comment]
I'm astounded how you clearly have no idea of how the development of Träwelling or a Scrum setup works.

For one, you (or any Träwelling user) don't have any entitlement that any issues are fixed or we provide Träwelling at all. This is a pure leisure project and _does it spark joy_ is always the main question.

I'd suggest you keep your expectations low and don't troll around, if you want anything you asked for resolved. Especially, don't throw punches if you clearly have no idea of the insides.

**Comment by Saeumer** [comment]
I observed this Issue and needed to make a Github account to inform you how you @jeyemwey has little to no expertise with Scrum, but that's common for a "Broadcast Engineer Student" that you have no expertise with agile development. 

Scrum operates in the manner described by @Oxbowatos. He stated first that you plan the Sprint which is correct because the issues are on a Backlog and must be planned (Sprint Planning) to be definedin the Sprint Backlog. 
The Story Points are alos crucial in determining how long someone should work on an issue, so that is right.
Utilizing Milestones and assigning Stories to Contributors is another Scrum method. 
He only left out the Daily Scrum Meetings and Refinements at the end, thus after you, he clearly has no grasp of Scrum? But after me (a scrum master at my company) I claim he has a better understanding of Scrum than you.

Also I went through the Repo and your Code, particularly the stuff that you did @jeyemwey, and I must say that you plainly have no understanding how to code. Also, like @Oxbowatos stated, the Repo Owner @MrKrisKrisu, as far as I can tell, does not have any coding knowledge.

It's incredibly disappointing to see such a brilliant idea being implemented by persons with little or no experience in coding, project management, or testing.
I see you also merged unfinished Stuff to the Productive Website which is rather amusing.

Next time you talk about Scrum, learn how it works first, and if you work on a Coding Project, please learn how to code first. 

I also observe that individuals who disliked the issue and liked the Repo Owner's and your comment lack experience in Project management and that they just simply soft-soap.

Thank you

**Comment by MrKrisKrisu** [comment]
Even though the conversation in this issue is locked and will remain so, I would like to briefly summarize and clarify the situation. Firstly, I believe this issue was created purely for trolling purposes, with both Oxbowatos and Saumer being new accounts created specifically to target us personally. This is not acceptable and both users have been [blocked from the whole organization](https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization).

Secondly, I want to clarify that this text represents **my personal view and does not reflect the opinion of the Träwelling team** from this point onwards. The main criticism and resulting suggestion was that Träwelling should establish better issue handling, including the use of Scrum and appropriate tools. However, I want to emphasize that **_Träwelling is not a company_** and all individuals who contribute to the project do so voluntarily in their spare time. There is no obligation to do anything or to organize anything. Since we do not have any regular working hours, an implementation of scrum simply wouldn’t be possible.

Personally, I sometimes scroll through issues and decide to work on one simply because I enjoy it, without any other motive. I don't receive any money or significant recognition for my contributions. So why should we organize something like Scrum for Träwelling? **There is nothing to organize.** Träwelling works well, with no **significant** bugs that affect its functionality (aside from some pages that are not performant or some ui improvements). The remaining issues are mostly feature requests, which will be addressed by someone who feels like doing it, eventually.

It's also worth noting that is truly audacious for someone to create a new Github account specially for this issue. This account mainly targets @jeyemwey and me personally - but also the Träwelling project as a whole, claiming that we can't program and have no experience in programming, and expressing disappointment that such people are managing such a "great project idea". My response to this is that if you can do it better, **the project is licensed under AGPL-3.0**. Fork it and do it better or start your own project. I won't be angry, and I'm looking forward to seeing your new ideas and good project management. I'll also take a close look at your code.

GitHub, and the OpenSource world in general, is such a great place with great people - who you don't seem to have fully understood.

Finally, I want to express how deeply disappointing it is that people go to such lengths to create new accounts and troll to this extent. It's also deeply hurtful on a personal level. I am very transparent and would be happy to invite you to our Discord server (https://discord.gg/72t7564ZbV) if you want to speak constructively about potential improvements. But please don't be an anon.
