### ISSUE TITLE
Server error while requesting polyline from the api

### ISSUE THREAD

**Issue by AdriDevelopsThings** [Traewelling/traewelling#1443]
**Describe the bug**
I get a server error while requesting polyline from the api:
```json
{
    "message": "Server Error"
}
```

**To Reproduce**
Make a GET request to `https://traewelling.de/api/v1/polyline/{ids}`, for example (I tested multiple statuses without authentication): https://traewelling.de/api/v1/polyline/849822.

**Expected behavior**
A GeoJSON object should be responded.

**Comment by HerrLevin** [comment]
This might be an easy fix. 

https://github.com/Traewelling/traewelling/blob/ad8021dc2b93e7a698ca8d9fac66a6e11a5e8f34/app/Http/Controllers/API/v1/StatusController.php#L422-L424

Throws an error, since no user is present when not logged in. 
```php
$this->authorize('view', $status);
```

could do the job. Though this needs to be cought. An ugly example:

```php
->filter(function(Status $status) { 
    $canView = true;
    try {
        $this->authorize('view', $status);
    } catch (AuthorizationException) {
        $canView = false;
    }
})
return $canView;       
```

I need to further investigate how we can use `->can()` without an authorized user. Maybe @MrKrisKrisu knows sth about that?
