### ISSUE TITLE
Better Emojis

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1462]
**Is your feature request related to a problem? Please describe.**
Traewelling is utilizing the default OS emojis, which are awful. 

**Describe the solution you'd like**
I'd want to have Twitter Emojis via Twemoji instead of the website's default Emojis.

**Describe alternatives you've considered**
Using other Emoji Fonts / Frameworks.

**Comment by MrKrisKrisu** [comment]
While I appreciate your suggestion of using Twemoji instead of the default emojis, I believe that it may not be the most practical solution as it would require additional development effort.

It is worth noting that the use of emojis in Traewelling is limited to the status text during check-ins, and I believe that this feature works as intended. I recommend that if you are unhappy with the default OS emojis, you could consider using a different operating system or installing a system-wide emoji pack.
