### ISSUE TITLE
Change Time/Date of träwel 

### ISSUE THREAD

**Issue by FinnHuelsbusch** [Traewelling/traewelling#1663]
I sometimes mess up the date / time when entering a new träwel. Currently it is not possible to change the time or date in the edit menu. So in order to change the date / time I need to delete an reenter the träwel. 

**Describe the solution you'd like**
Edit the date / time of an träwel. 

**Describe alternatives you've considered**
Non

**Additional context**
![image](https://github.com/Traewelling/traewelling/assets/61464543/b90f54b5-700f-49b9-9afd-42afd457e936)
Current menu has no option to change the date of träwel.

**Comment by MrKrisKrisu** [comment]
I am not sure if I have understood the background of your issue correctly. In my opinion, you want to move an incorrectly performed checkin to another day or time, if you have selected the wrong one.

In that case, I would actually advise you to delete the checkin and then check into the correct train. Features like seeing which people are also on the train with you don't make sense anymore otherwise.

However, if you think that you can correct the departure and arrival time, e.g. if our datta differs from the actual data we get from the "real time" schedule, then the feature from Issue #1433 / PR #1439 may fit your scenario.

I'll close here, if you have no further information / questions. :)
