### ISSUE TITLE
Wrong Line on map and Distance on specific bus

### ISSUE THREAD

**Issue by sinsa92** [Traewelling/traewelling#1726]
**Describe the bug**
Bus 120 from Berlin Hbf to Berlin Seydlitzstr. draws a weird line on the map of like 14km, while the actual route is like 3 blocks. This only happens in the direction towards Seydlitzstr., the opposite direction is correct.

120 Hbf->Seydlitzstr (wrong line on map/distance): https://traewelling.de/status/1199392

120 Seydlitzstr->Hbf (correct line and distance): https://traewelling.de/status/1200370

**To Reproduce**
Go to Berlin Hbf and check into bus 120 towards Seydlitzstr. until the terminus.

**Expected behavior**
I expect the line and distance to be similar like in checkin #1200370.

**Smartphone (please complete the following information):**

- Device: iPhone 8+
- OS: iOS 15.7.1
- Browser: Safari
- Version: I don't know, most likely latest stable

**Comment by MrKrisKrisu** [comment]
My first assumption was that this could be a problem with the Brouter integration. But the route was not sent through Brouter, according to the log there is only one event for the status, otherwise there would be more. In addition, this is a bus connection, which should not be generated there anyway. 

```
[2023-07-08 21:05:41] production.INFO: Dispatching UserCheckedIn event for status#1199392  
``` 

Then I looked at the data we received by DB-Rest / HAFAS:
https://v6.db.transport.rest/trips/1%7C1730433%7C0%7C80%7C9072023?polyline=true

This is the full polyline, so it seems there is something cutted wrong here.
![image](https://github.com/Traewelling/traewelling/assets/4103693/b52362a3-3939-4384-bea6-985a28afe345)

**Comment by HerrLevin** [comment]
Closing, cause this seems to be a data provider issue
