### ISSUE TITLE
Cancelled Stops can be chosen as an Exit of the check-in.

### ISSUE THREAD

**Issue by SoraCent** [Traewelling/traewelling#1743]
**Describe the bug**
Normally, you cannot choose cancelled stops as exits when checking in for a train.
However, you can do so when editing your check-in.

**To Reproduce**

1. Check-in to a train-trip which has cancelled Stops
2. Edit the check-in
3. Change your Exit while editing and choose a Cancelled Stop.
4. Your Check-in Exit has been changed to the Cancelled Stop.

**Expected behavior**
The ability to check into cancelled stops should be prevented, same like when creating the Check-in.

**Screenshots**

You see that you cannot check in to the cancelled stop while creating the check-in.
![grafik](https://github.com/Traewelling/traewelling/assets/46794893/4fc6da12-e190-433e-a5c5-4a5ee4d8374e)

However, while editing it, you can.
![grafik](https://github.com/Traewelling/traewelling/assets/46794893/2cacde49-9b27-4884-b0ca-7f44322c84be)
![grafik](https://github.com/Traewelling/traewelling/assets/46794893/361f824a-195d-45e7-a93d-831a72380dde)

**Desktop (please complete the following information):**

Cross-Browser and OS

**Additional context**
The bug was discovered by another person (on the same train as in the screenshots), and when I tested it, it also occurred to me.

**Comment by vainamov** [comment]
Coming to think of it, I wouldn't see this as a bug. Editing the status allows for manual correction of false HAFAS data like arrival and departure times, so why not also allow the user to select a stop that HAFAS considers canceled? It might still be in service and HAFAS just doesn't know.

But in order to prevent accidental selection of canceled stops, a message could be added for those stations, so the user may double-check that the selected station is correct.

**Comment by MrKrisKrisu** [comment]
I completely agree with @vainamov  and would not see this as a bug, but as a way that you can correct your checkins owed due to incorrect HAFAS data. :)
