### ISSUE TITLE
FlixTrain (FLX) is marked as regional train, not high-speed/long-distance train

### ISSUE THREAD

**Issue by rugk** [Traewelling/traewelling#2160]
### Describe the bug

E.g. the train https://traewelling.de/status/1707094 is shown as a FLX regional train, not a high-speed/long-distance train. Given what it rides it is certainly a long distance though.😉

### Steps to reproduce

1. Search for a Flixtrain at a station.
2. Press the filter for high-speed trains.
3. FlixTtain is gone.
4. Revert and instead press filter for regional trains.
5. Flixtrain is there.

### Browser console logs

```bash
N/A
```

### Browser

Firefox

**Comment by marhei** [comment]
Flixtrain publishes this train in the Hafas as an Interregio  train, which is regarded as regional transport in most countries.

The behaviour you describe also exists on bahn.de: your Flixtrain is not displayed when you explicitly search for long-distance services only, but is displayed for regional services.

The error is therefore not with Träwelling, but in the data that Flixtrain itself publishes. I can well imagine that Flixtrain does this on purpose in order to appear in a search for regional transport and thus attract the attention of more price-sensitive customers träwelling with the Deutschland-Ticket.

**Comment by rugk** [comment]
> does this on purpose in order to appear in a search for regional transport and thus attract the attention of more price-sensitive customers träwelling with the Deutschland-Ticket.

Hmm, which would explain why they always say it like 5 times there, that DTicket is _not_ valid and DB tickets neither and you need a FlixTrain ticket… :thinking: 

A workaround just for trawelling maybe would be an idea, as it is – I mean come on – it's factually wrong hmm. :thinking:

**Comment by marhei** [comment]
I don't think it's a good idea to create a workaround for "wrong" data from individual trains.

You can send a mail to Flixtrain, but there is nothing to do on the Träwelling side, because it interprets the data as intended.

**Comment by jheubuch** [comment]
I also think that the data shouldn't be modified by Träwelling. I guess this would be way too much effort for way too little benefit.

If Flixtrain publishes their trains as `regionalExp` it is wanted by them as is - so they're describing themselves as (fast) regional transport.
