### ISSUE TITLE
Filtering by trip type does not seem to work. 

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#273]
Filtering by trip type does not seem to work. The error has yet to be confirmed.

![image](https://user-images.githubusercontent.com/4103693/116786688-61f70500-aaa0-11eb-946b-cf2b5f498e6e.png)

**Comment by MrKrisKrisu** [comment]
The `Fernverkehr`/`express` filter doesn't show any trains. Other filters work correctly.

**Comment by EventHorizon8** [comment]
Good afternoon! I want to fix this bug but I'm not sure about what kind of trains you expect to see.
But I found keys description from api which used in this application (key - description):
nationalExpress - Include InterCityExpress (ICE)
national - Include InterCity & EuroCity (IC/EC)
regionalExp - Include RegionalExpress & InterRegio (RE/IR)
regional - Include Regio (RB)

What keys relate to **Fernverkehr/express** filter and what keys to **regional**?

**Comment by HerrLevin** [comment]
Hi, I just skimmed our source code for this and `express` is a custom key to combine `nationalExpress` and `national` from the API since IC/EC and ICE are long distance trains. 

You can fix this by changing $travelType-value in line 89 on `app/Http/Controllers/TransportController.php` from `nationalExpress` to `express`. I currently don't have the time to write this fix but I could merge a PR from you for that!
