### ISSUE TITLE
Check-In with trains that are late

### ISSUE THREAD

**Issue by macwinnie** [Traewelling/traewelling#575]
**Describe the bug**

Today ICE 526 was late (+65 when leaving MH) and could be reached by ICE 789.

Checkin was not permitted.

**Expected behavior**
Checkin should have been permitted.

**Screenshots**

![0C62E193-1B24-4A1E-898F-74E60D01A546](https://user-images.githubusercontent.com/1001936/138162965-5b31ece9-93ad-4217-bdf9-96ce0c345083.jpeg)

**Smartphone (please complete the following information):**

- Device: iPhone12
- OS: iOS 15
- Browser Firefox
- Version 38

**Comment by karlbeecken** [comment]
According to my research, this issue is caused by comparing the planned departure/arrival times instead of the real-time data in [this function](https://github.com/Traewelling/traewelling/blob/5357cd5541e751beb4872f0bd594d42a593eeeae/app/Http/Controllers/TransportController.php#L412). A dirty fix would be to increase the tolerance (currently at 10 minutes, maybe push it up to 60) but this would defeat the purpose of this function. To fix this issue in a nice way, the real-time data is needed in this function. As I'm only beginning to look through the code, I have no idea how to get the data there, maybe someone from the team can help by hitting me up with the right information or just fixing this real quick, as this shouldn't be the greatest hassle.

**Comment by MrKrisKrisu** [comment]
Our backend can now force checkins. This can already be used via the API. The frontend has not yet implemented this possibility.

https://github.com/Traewelling/traewelling/blob/18f2d105cb6c22b5ef20450ef72cd35dc6982db6/app/Http/Controllers/Backend/Transport/TrainCheckinController.php#L61
